//user Types
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";

//Profile Types
export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

//Tournament Types
export const ADD_TOURNAMENT_REQUEST  = "ADD_TOURNAMENT_REQUEST";
export const ADD_TOURNAMENT_SUCCESS  = "ADD_TOURNAMENT_SUCCESS";
export const ADD_TOURNAMENT_FAIL  = "ADD_TOURNAMENT_FAIL";

export const GET_TOURNAMENT_REQUEST  = "GET_TOURNAMENT_REQUEST";
export const GET_TOURNAMENT_SUCCESS  = "GET_TOURNAMENT_SUCCESS";
export const GET_TOURNAMENT_FAIL  = "GET_TOURNAMENT_FAIL";

export const DELETE_TOURNAMENT_REQUEST  = "DELETE_TOURNAMENT_REQUEST";  
export const DELETE_TOURNAMENT_SUCCESS  = "DELETE_TOURNAMENT_SUCCESS";
export const DELETE_TOURNAMENT_FAIL  = "DELETE_TOURNAMENT_FAIL";

export const EDIT_TOURNAMENT_REQUEST  = "EDIT_TOURNAMENT_REQUEST";
export const EDIT_TOURNAMENT_SUCCESS  = "EDIT_TOURNAMENT_SUCCESS";
export const EDIT_TOURNAMENT_FAIL  = "EDIT_TOURNAMENT_FAIL";

export const LIST_TOURNAMENT_REQUEST  = "LIST_TOURNAMENT_REQUEST";
export const LIST_TOURNAMENT_SUCCESS  = "LIST_TOURNAMENT_SUCCESS";
export const LIST_TOURNAMENT_FAIL  = "LIST_TOURNAMENT_FAIL";

export const ADD_PLAYER_TO_TOURNAMENT_REQUEST  = "ADD_PLAYER_TO_TOURNAMENT_REQUEST";
export const ADD_PLAYER_TO_TOURNAMENT_SUCCESS  = "ADD_PLAYER_TO_TOURNAMENT_SUCCESS";
export const ADD_PLAYER_TO_TOURNAMENT_FAIL  = "ADD_PLAYER_TO_TOURNAMENT_FAIL";

export const REMOVE_PLAYER_FROM_TOURNAMENT_REQUEST  = "REMOVE_PLAYER_FROM_TOURNAMENT_REQUEST";  
export const REMOVE_PLAYER_FROM_TOURNAMENT_SUCCESS  = "REMOVE_PLAYER_FROM_TOURNAMENT_SUCCESS";
export const REMOVE_PLAYER_FROM_TOURNAMENT_FAIL  = "REMOVE_PLAYER_FROM_TOURNAMENT_FAIL";


//playerlist
export const UPDATE_PLAYER_REQUEST  = "UPDATE_PLAYER_REQUEST";
export const UPDATE_PLAYER_SUCCESS  = "UPDATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_FAIL  = "UPDATE_PLAYER_FAIL";

export const GET_PLAYER_REQUEST  = "GET_PLAYER_REQUEST";
export const GET_PLAYER_SUCCESS  = "GET_PLAYER_SUCCESS";
export const GET_PLAYER_FAIL  = "GET_PLAYER_FAIL";

export const LIST_PLAYER_REQUEST  = "LIST_PLAYER_REQUEST";
export const LIST_PLAYER_SUCCESS  = "LIST_PLAYER_SUCCESS";
export const LIST_PLAYER_FAIL  = "LIST_PLAYER_FAIL";

export const DELETE_PLAYER_REQUEST  = "DELETE_PLAYER_REQUEST";  
export const DELETE_PLAYER_SUCCESS  = "DELETE_PLAYER_SUCCESS";
export const DELETE_PLAYER_FAIL  = "DELETE_PLAYER_FAIL";

export const ADD_PLAYER_REQUEST  = "ADD_PLAYER_REQUEST";
export const ADD_PLAYER_SUCCESS  = "ADD_PLAYER_SUCCESS";
export const ADD_PLAYER_FAIL  = "ADD_PLAYER_FAIL";

//draws

export const CREATE_DRAWS_REQUEST  = "CREATE_DRAWS_REQUEST";
export const CREATE_DRAWS_SUCCESS  = "CREATE_DRAWS_SUCCESS";
export const CREATE_DRAWS_FAIL  = "CREATE_DRAWS_FAIL";

export const FETCH_DRAWS_REQUEST  = "FETCH_DRAWS_REQUEST";
export const FETCH_DRAWS_SUCCESS  = "FETCH_DRAWS_SUCCESS";
export const FETCH_DRAWS_FAIL  = "FETCH_DRAWS_FAIL";

//MATCHES
export const SHOW_MATCHES_REQUEST  = "SHOW_MATCHES_REQUEST";
export const SHOW_MATCHES_SUCCESS  = "SHOW_MATCHES_SUCCESS";
export const SHOW_MATCHES_FAIL  = "SHOW_MATCHES_FAIL";

export const GIVE_BYES_REQUEST  = "GIVE_BYES_REQUEST";
export const GIVE_BYES_SUCCESS  = "GIVE_BYES_SUCCESS";
export const GIVE_BYES_FAIL  = "GIVE_BYES_FAIL";

export const GET_PLAYER_DRAW_REQUEST  = "GET_PLAYER_DRAW_REQUEST";
export const GET_PLAYER_DRAW_SUCCESS  = "GET_PLAYER_DRAW_SUCCESS";
export const GET_PLAYER_DRAW_FAIL  = "GET_PLAYER_DRAW_FAIL";

export const SEARCH_PLAYER_REQUEST  = "SEARCH_PLAYER_REQUEST";
export const SEARCH_PLAYER_SUCCESS  = "SEARCH_PLAYER_SUCCESS";
export const SEARCH_PLAYER_FAIL  = "SEARCH_PLAYER_FAIL";