# Generated by Django 3.2.9 on 2022-02-08 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
